jenkins:
  controller:
    componentName: "jenkins"
    # Usamos NodePort ou LoadBalancer para facilitar o acesso local no Kind
    serviceType: "NodePort"
    servicePort: 8080
    nodePort: 32000 # Porta fixa para acessar via localhost no Kind

    # image: "jenkins/jenkins"
    # tag: "2.479.3-jdk17"
    
    # Configuração básica de recursos
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "2Gi"

    # Persistência de dados para não perder os jobs ao reiniciar o pod
    persistence:
      enabled: true
      size: 8Gi
