apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd # Namespace onde o ArgoCD está instalado
spec:
  project: default
  source:
    repoURL: 'https://github.com/mjsbicigo/sandbox.git'
    targetRevision: HEAD
    path: 'apps/jenkins' # Onde está o nosso Helm Chart do Jenkins
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins # Namespace onde o Jenkins será criado no cluster
  syncPolicy:
    automated:
      prune: true # Deleta recursos no cluster se forem removidos do Git
      selfHeal: true # Corrige o cluster automaticamente se alguém alterar algo manualmente
