apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.9.54
    helm:
      values: |
        controller:
          admin:
            password: "AdminPassword123"
          serviceType: "NodePort" # Ou LoadBalancer / ClusterIP com Ingress
          persistence:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
