apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-metrics-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-metrics-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: queue-metrics-api

  template:
    metadata:
      labels:
        app: queue-metrics-api

    spec:
      serviceAccountName: queue-metrics-api

      containers:
      - name: queue-metrics-api

        image: marciosbicigo/get-metrics-oci-queue:1.1

        ports:
        - containerPort: 8080

        env:
        - name: Queue__Id
          valueFrom:
            secretKeyRef:
              name: queue-metrics-secret
              key: queue-id
---
apiVersion: v1
kind: Service
metadata:
  name: queue-metrics-api

spec:
  selector:
    app: queue-metrics-api

  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: queue-metrics-secret

type: Opaque

stringData:
  queue-id: "Queue_OCID_HERE"
